package interfaces;

import controle.ControladorCadastroProfessoresEfetivos;
import entidade.ProfessorEfetivado;
import javax.swing.JOptionPane;


public class JanelaCadastroProfessoresEfetivados extends javax.swing.JFrame {

    ControladorCadastroProfessoresEfetivos controlador;
    ProfessorEfetivado[] professores_cadastrados;

    public JanelaCadastroProfessoresEfetivados(ControladorCadastroProfessoresEfetivos controlador) {
        this.controlador = controlador;
        professores_cadastrados = ProfessorEfetivado.getVisões();
        initComponents();
        limparCampos();
    }

    private void limparCampos(){
        nomeTextField.setText("");
        cpfTextField.setText("");
        emailTextField.setText("");
        titulaçãoTextField.setText("");
    }
    
    private ProfessorEfetivado obterProfessorEfetivadoInformado(){
        String cpf = cpfTextField.getText();
        if (cpf.isEmpty()) return null;
        String nome = nomeTextField.getText();
        if (nome.isEmpty()) return null;
        String titulação = titulaçãoTextField.getText();
        if (titulação.isEmpty()) return null;
        String email = emailTextField.getText();
        if (email.isEmpty()) return null;
        return new ProfessorEfetivado(nome, cpf, titulação, email);
    }

    private JanelaCadastroProfessoresEfetivados() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        professores_cadastradosComboBox = new javax.swing.JComboBox<>();
        nomeTextField = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        cpfTextField = new javax.swing.JTextField();
        titulaçãoLabel = new javax.swing.JLabel();
        titulaçãoTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        comandosPanel = new javax.swing.JPanel();
        inserirButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        alterarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Professores Efetivos");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        professores_cadastradosComboBox.setModel(professores_cadastrados);
        professores_cadastradosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professores_cadastradosComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(professores_cadastradosComboBox, gridBagConstraints);

        nomeTextField.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 332;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 0, 0, 6);
        getContentPane().add(nomeTextField, gridBagConstraints);

        nomeLabel.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 39, 0, 0);
        getContentPane().add(nomeLabel, gridBagConstraints);

        cpfLabel.setText("CPF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 39, 0, 0);
        getContentPane().add(cpfLabel, gridBagConstraints);

        cpfTextField.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        getContentPane().add(cpfTextField, gridBagConstraints);

        titulaçãoLabel.setText("Titulação");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 38, 0, 0);
        getContentPane().add(titulaçãoLabel, gridBagConstraints);

        titulaçãoTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 103;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        getContentPane().add(titulaçãoTextField, gridBagConstraints);

        emailTextField.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 336;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 6);
        getContentPane().add(emailTextField, gridBagConstraints);

        emailLabel.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 39, 0, 0);
        getContentPane().add(emailLabel, gridBagConstraints);

        comandosPanel.setMinimumSize(new java.awt.Dimension(200, 35));
        comandosPanel.setPreferredSize(new java.awt.Dimension(200, 35));
        comandosPanel.setLayout(new java.awt.GridBagLayout());

        inserirButton.setText("Inserir");
        inserirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirProfessorEfetivado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 6, 2);
        comandosPanel.add(inserirButton, gridBagConstraints);

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparPainel(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        comandosPanel.add(limparButton, gridBagConstraints);

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarProfessorEfetivado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        comandosPanel.add(consultarButton, gridBagConstraints);

        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarProfessorEfetivado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        comandosPanel.add(alterarButton, gridBagConstraints);

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerProfessorEfetivado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        comandosPanel.add(removerButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 213;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(85, 14, 48, 6);
        getContentPane().add(comandosPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirProfessorEfetivado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirProfessorEfetivado
        ProfessorEfetivado professorEfetivado = obterProfessorEfetivadoInformado();
        String mensagem_erro = null;
        if (professorEfetivado != null) mensagem_erro = controlador.inserirProfessorEfetivo(professorEfetivado);
        else mensagem_erro = "Algum atributo do professor não foi informado";
        if (mensagem_erro == null) {
            informarSucesso("Inserção bem sucedida");
        }
        else informarErro(mensagem_erro);
    }//GEN-LAST:event_inserirProfessorEfetivado

    private void consultarProfessorEfetivado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarProfessorEfetivado
        String cpf = cpfTextField.getText();
        String mensagem_erro = null;
        ProfessorEfetivado professorEfetivado = null;
        if (!cpf.isEmpty()){
            professorEfetivado = ProfessorEfetivado.buscarProfessorEfetivado(cpf);
            if (professorEfetivado == null) mensagem_erro="Professor não Cadastrado";
        } else mensagem_erro = "CPF do professor não informado";
        if (mensagem_erro == null){
            nomeTextField.setText(professorEfetivado.getNome());
            emailTextField.setText(professorEfetivado.getEmail());
            titulaçãoTextField.setText(professorEfetivado.getTitulação());
        } else informarErro(mensagem_erro);
    }//GEN-LAST:event_consultarProfessorEfetivado

    private void limparPainel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparPainel
        limparCampos();
    }//GEN-LAST:event_limparPainel

    private void alterarProfessorEfetivado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarProfessorEfetivado
        ProfessorEfetivado professorEfetivado = obterProfessorEfetivadoInformado();
        String mensagem_erro = null;
        if (professorEfetivado != null) mensagem_erro = controlador.alterarProfessorEfetivo(professorEfetivado);
        else mensagem_erro = "CPF do professor não informado";
        if (mensagem_erro == null) informarSucesso("Alteração bem sucedida");
        else informarErro(mensagem_erro);
    }//GEN-LAST:event_alterarProfessorEfetivado

    private void removerProfessorEfetivado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerProfessorEfetivado
        String cpf = cpfTextField.getText();
        String mensagem_erro = null;
        if (!cpf.isEmpty()) mensagem_erro = controlador.removerProfessorEfetivo(cpf);
        else mensagem_erro = "CPF do professor não informado";
        if (mensagem_erro == null) informarSucesso("Remoção bem sucedida");
        else informarErro(mensagem_erro);
    }//GEN-LAST:event_removerProfessorEfetivado

    private void professores_cadastradosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professores_cadastradosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_professores_cadastradosComboBoxActionPerformed

    private void informarSucesso(String mensagem) {
        JOptionPane.showConfirmDialog(this, mensagem, "Informação", JOptionPane.INFORMATION_MESSAGE);
    }
    private void informarErro(String mensagem){
        JOptionPane.showMessageDialog(this, mensagem, "Erro", JOptionPane.ERROR_MESSAGE);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroProfessoresEfetivados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroProfessoresEfetivados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroProfessoresEfetivados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroProfessoresEfetivados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastroProfessoresEfetivados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarButton;
    private javax.swing.JPanel comandosPanel;
    private javax.swing.JButton consultarButton;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField cpfTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton inserirButton;
    private javax.swing.JButton limparButton;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JComboBox<String> professores_cadastradosComboBox;
    private javax.swing.JButton removerButton;
    private javax.swing.JLabel titulaçãoLabel;
    private javax.swing.JTextField titulaçãoTextField;
    // End of variables declaration//GEN-END:variables
}
