package interfaces;

import controle.ControladorCadastroFaculdades;
import controle.ControladorCadastroProfessoresEfetivos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import persistência.BD;

public class JanelaContrataçãoProfessores extends javax.swing.JFrame {

    /**
     * Creates new form JanelaContrataçãoProfessores
     */
    public JanelaContrataçãoProfessores() throws SQLException {
        BD.criaConexão();
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contratação_professoresMenuBar = new javax.swing.JMenuBar();
        professor_efetivadoMenu = new javax.swing.JMenu();
        cadastrar_professor_efetivadoMenuItem = new javax.swing.JMenuItem();
        faculdadeMenu = new javax.swing.JMenu();
        cadastrar_faculdadeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contratação de Professores");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                terminarSistema(evt);
            }
        });

        professor_efetivadoMenu.setText("Professores Efetivos");

        cadastrar_professor_efetivadoMenuItem.setText("Cadastrar");
        cadastrar_professor_efetivadoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProfessorEfetivado(evt);
            }
        });
        professor_efetivadoMenu.add(cadastrar_professor_efetivadoMenuItem);

        contratação_professoresMenuBar.add(professor_efetivadoMenu);

        faculdadeMenu.setText("Faculdades");

        cadastrar_faculdadeMenuItem.setText("Cadastrar");
        cadastrar_faculdadeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFaculdade(evt);
            }
        });
        faculdadeMenu.add(cadastrar_faculdadeMenuItem);

        contratação_professoresMenuBar.add(faculdadeMenu);

        setJMenuBar(contratação_professoresMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarProfessorEfetivado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProfessorEfetivado
        new ControladorCadastroProfessoresEfetivos();
    }//GEN-LAST:event_cadastrarProfessorEfetivado

    private void terminarSistema(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_terminarSistema
        try {
            BD.fechaConexão();
            System.exit(0);
        } catch (SQLException ex) {
            Logger.getLogger(JanelaContrataçãoProfessores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_terminarSistema

    private void cadastrarFaculdade(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFaculdade
        new ControladorCadastroFaculdades();
    }//GEN-LAST:event_cadastrarFaculdade

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaContrataçãoProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaContrataçãoProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaContrataçãoProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaContrataçãoProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JanelaContrataçãoProfessores().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JanelaContrataçãoProfessores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrar_faculdadeMenuItem;
    private javax.swing.JMenuItem cadastrar_professor_efetivadoMenuItem;
    private javax.swing.JMenuBar contratação_professoresMenuBar;
    private javax.swing.JMenu faculdadeMenu;
    private javax.swing.JMenu professor_efetivadoMenu;
    // End of variables declaration//GEN-END:variables
}
